force-app/main/default/objects/Log_Hour__c/Log_Hour__c.object-meta.xml
<CustomObject>
    <label>Log Hour</label>
    <nameField>
        <displayFormat>LOG-{000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Hour__c/fields/Daily_Log_Hour__c.field-meta.xml
<CustomField>
    <fullName>Daily_Log_Hour__c</fullName>
    <label>Daily Log Hour</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Hour__c/fields/Daily_Log_Mins__c.field-meta.xml
<CustomField>
    <fullName>Daily_Log_Mins__c</fullName>
    <label>Daily Log Mins</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>00</label>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log_Hour__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <label>Task</label>
    <referenceTo>Task__c</referenceTo>
    <relationshipLabel>Log Hours</relationshipLabel>
    <relationshipName>Log_Hours</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DailyTimeSheetControllerTest.cls
/**
 * @author            : Vrushabh Uprikar
 * @last modified on  : 05-10-2021
 * @last modified by  : Vrushabh Uprikar
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   01-10-2021   Vrushabh Uprikar   Initial Version
**/
@isTest
public class DailyTimeSheetControllerTest 
{
	@isTest
    public static void getAllDailyLogsTest()
    {
        Task__c task = new Task__c();
        task.Name = 'taskTestName';
        insert task;
        
        Log_Hour__c logHour = new Log_Hour__c();
        logHour.Task__c = task.Id;
        logHour.Date__c = date.newInstance(2021, 09, 15);
        logHour.Daily_Log_Hour__c = '08';
        logHour.Daily_Log_Mins__c = '30';
        insert logHour;
        
        List<SObject> listSobject = DailyTimeSheetController.getAllDailyLogs(2021);
        Log_Hour__c logHourAssert = (Log_Hour__c)listSobject[0];
        
        System.assertEquals(logHourAssert.Date__c, logHour.Date__c);
    }
}