force-app/main/default/objects/Log_Hour__c/Log_Hour__c.object-meta.xml
<CustomObject>
    <label>Log Hour</label>
    <nameField>
        <displayFormat>LOG-{000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Hour__c/fields/Daily_Log__c.field-meta.xml
<CustomField>
    <fullName>Daily_Log__c</fullName>
    <label>Daily Log</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DailyTimeSheetController.cls
/**
 * @author            : Vrushabh Uprikar
 * @last modified on  : 23-09-2021
 * @last modified by  : Vrushabh Uprikar
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   23-09-2021   Vrushabh Uprikar   Initial Version
**/
public with sharing class DailyTimeSheetController 
{
   @AuraEnabled(cacheable = true)
   public static List<SObject> getAllDailyLogs(String year) // get all logs by year
   {
      String query ='Select Id, Name, Daily_Log__c, Date__c, Notes__c From Log_Hour__c Where CALENDAR_YEAR(Date__c) = '+year;
      List<SObject> test1 = Database.query(query);
      System.debug('any: ' + test1);      
      return test1;
   }
}